name: neoflex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.11
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.6
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png" 